# Generated by Django 6.0.5 on 2026-06-06 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_Page_funcionalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='main_Page_funcionalidades.livro')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('livro', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('pos_x', models.IntegerField(default=100)),
                ('pos_y', models.IntegerField(default=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main_Page_funcionalidades.capitulo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='main_Page_funcionalidades.capitulo')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_destino', to='main_Page_funcionalidades.card')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_origem', to='main_Page_funcionalidades.card')),
            ],
            options={
                'unique_together': {('origem', 'destino')},
            },
        ),
    ]
