# Generated by Django 6.0.5 on 2026-06-06 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_Page_funcionalidades', '0003_card_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('conteudo', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitulos', to='main_Page_funcionalidades.card')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
