# Generated by Django 6.0.5 on 2026-06-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_Page_funcionalidades', '0005_anotacaocompartilhada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tradicao', models.CharField(choices=[('americana', 'Americana'), ('japonesa', 'Japonesa')], max_length=20)),
                ('biografia', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autores/')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.CharField(blank=True, max_length=20)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='obras_capas/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='main_Page_funcionalidades.autor')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
